const http=require('http'),fs=require('fs'),path=require('path');const {extractRules,verifyDraft}=require('./lib/core');
const db={meetings:[],segments:[],drafts:[],events:[],audit:[]};
function seed(){const m={id:'MTG-001',project_id:'PRJ-001',title:'防火門進度協調會',date:'2026-09-23',time:'14:00',location:'工務所會議室',organizer:'工地主任',agenda:'防火門進度、五金交期、七樓裝修介面',status:'REVIEW_PENDING',source:'DEMO'};const s={id:'SEG-001',meeting_id:m.id,start_ms:120000,end_ms:145000,speaker:'工地主任',text:'防火門目前完成32樘，剩18樘。五金還有6組沒到，永盛說下週三會全部補齊。採購明天下班前再確認一次，如果再延誤會影響七樓裝修。'};db.meetings.push(m);db.segments.push(s);db.drafts.push(...extractRules(m,[s]))}seed();
const getMeeting=id=>db.meetings.find(x=>x.id===id);
function json(res,code,data){res.writeHead(code,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))}
function body(req,cb){let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{cb(null,JSON.parse(b||'{}'))}catch(e){cb(e)}})}
function view(){const meeting=db.meetings[db.meetings.length-1];return {meeting,meetings:db.meetings,segments:db.segments.filter(x=>x.meeting_id===meeting.id),drafts:db.drafts.filter(x=>x.meeting_id===meeting.id),events:db.events.filter(x=>x.meeting_id===meeting.id),audit:db.audit.filter(x=>x.meeting_id===meeting.id)}}
http.createServer((req,res)=>{
 if(req.url==='/api/v1/demo'&&req.method==='GET')return json(res,200,view());
 if(req.url==='/api/v1/meetings'&&req.method==='POST')return body(req,(err,b)=>{if(err)return json(res,400,{error:{code:'BAD_JSON'}});const required=['title','date','time'];const miss=required.filter(k=>!String(b[k]||'').trim());if(miss.length)return json(res,422,{error:{code:'GATE_VIOLATION',message:'必填：'+miss.join(', ')}});const id='MTG-'+String(db.meetings.length+1).padStart(3,'0');const m={id,project_id:b.project_id||'PRJ-001',title:b.title.trim(),date:b.date,time:b.time,location:b.location||'',organizer:b.organizer||'',agenda:b.agenda||'',meeting_url:b.meeting_url||'',status:'DRAFT',source:'LINE_LIFF_INPUT',created_at:new Date().toISOString()};db.meetings.push(m);db.audit.push({id:'AUD-'+Date.now(),meeting_id:id,action:'CREATE_MEETING',before:null,after:'DRAFT',actor:b.actor||'LINE_USER',at:new Date().toISOString()});json(res,201,m)});
 let pub=req.url.match(/^\/api\/v1\/meetings\/([^/]+)\/publish$/);if(pub&&req.method==='POST')return body(req,(err,b)=>{const m=getMeeting(pub[1]);if(!m)return json(res,404,{error:{code:'NOT_FOUND'}});if(m.status!=='DRAFT')return json(res,422,{error:{code:'INVALID_STATE'}});if(!b.approver)return json(res,422,{error:{code:'GATE_VIOLATION',message:'發布會議卡需要人工確認'}});const before=m.status;m.status='SCHEDULED';m.published_by=b.approver;m.published_at=new Date().toISOString();db.audit.push({id:'AUD-'+Date.now(),meeting_id:m.id,action:'PUBLISH_LINE_CARD',before,after:m.status,actor:b.approver,at:m.published_at});json(res,200,{meeting:m,card:{type:'flex',altText:m.title+'｜'+m.date+' '+m.time,share_url:'/line.html?meeting='+m.id}})});
 let inp=req.url.match(/^\/api\/v1\/meetings\/([^/]+)\/input$/);if(inp&&req.method==='POST')return body(req,(err,b)=>{const m=getMeeting(inp[1]);if(!m)return json(res,404,{error:{code:'NOT_FOUND'}});if(!String(b.text||'').trim())return json(res,422,{error:{code:'GATE_VIOLATION',message:'輸入內容不可空白'}});const s={id:'SEG-'+String(db.segments.length+1).padStart(3,'0'),meeting_id:m.id,start_ms:0,end_ms:0,speaker:b.speaker||'LINE使用者',text:b.text.trim(),source:'LINE_TEXT_INPUT',created_at:new Date().toISOString()};db.segments.push(s);const ds=extractRules(m,[s]);db.drafts.push(...ds);m.status='REVIEW_PENDING';db.audit.push({id:'AUD-'+Date.now(),meeting_id:m.id,action:'LINE_INPUT_TO_DRAFT',before:'SCHEDULED',after:'REVIEW_PENDING',actor:b.speaker||'LINE_USER',evidence:s.id,at:new Date().toISOString()});json(res,201,{segment:s,drafts:ds})});
 let edit=req.url.match(/^\/api\/v1\/draft-events\/([^/]+)$/);if(edit&&req.method==='PATCH')return body(req,(err,b)=>{const d=db.drafts.find(x=>x.id===edit[1]);if(!d)return json(res,404,{error:{code:'NOT_FOUND'}});if(!b.reviewer||!String(b.reason||'').trim())return json(res,422,{error:{code:'GATE_VIOLATION',message:'修改必須有 Reviewer 與 Reason'}});const before=JSON.parse(JSON.stringify(d));if(b.subject)d.subject=b.subject.trim();if('owner_text'in b)d.owner_text=b.owner_text;if('relative_due_text'in b)d.relative_due_text=b.relative_due_text;d.human_revision={subject:d.subject,owner_text:d.owner_text||null,relative_due_text:d.relative_due_text||null,reason:b.reason,reviewer:b.reviewer,at:new Date().toISOString()};db.audit.push({id:'AUD-'+Date.now(),meeting_id:d.meeting_id,action:'EDIT_DRAFT',before:{subject:before.subject,owner_text:before.owner_text||null,relative_due_text:before.relative_due_text||null},after:d.human_revision,actor:b.reviewer,reason:b.reason,at:d.human_revision.at});json(res,200,d)});
 if(req.url.startsWith('/api/v1/draft-events/')&&req.url.endsWith('/verify')&&req.method==='POST'){let b='';req.on('data',c=>b+=c);return req.on('end',()=>{try{const x=JSON.parse(b||'{}'),id=req.url.split('/')[4],d=db.drafts.find(z=>z.id===id);if(!d)return json(res,404,{error:{code:'NOT_FOUND'}});const seg=db.segments.filter(s=>s.meeting_id===d.meeting_id),e=verifyDraft(d,x.reviewer,seg);e.meeting_id=d.meeting_id;db.events.push(e);db.audit.push({id:'AUD-'+Date.now(),meeting_id:d.meeting_id,action:'VERIFY_EVENT',before:'REVIEW_PENDING',after:'OPEN',actor:x.reviewer,evidence:e.evidence.map(q=>q.segment_id),at:e.verified_at});json(res,200,e)}catch(e){json(res,422,{error:{code:e.code||'BAD_REQUEST',message:e.message}})})}
 const f=req.url==='/'?'public/line.html':'public'+req.url.split('?')[0],p=path.join(__dirname,f);if(p.startsWith(path.join(__dirname,'public'))&&fs.existsSync(p)){res.writeHead(200,{'content-type':p.endsWith('.html')?'text/html; charset=utf-8':'text/plain'});return fs.createReadStream(p).pipe(res)}json(res,404,{error:{code:'NOT_FOUND'}})
}).listen(process.env.PORT||3000,()=>console.log('Construction Meeting OS LINE Gateway http://localhost:'+(process.env.PORT||3000)));